services:
  app-service:
    build: ./app-service
    container_name: app-service
    ports:
      - "8001:8001"
    environment:
      - RECOMMENDER_URL=http://recommender-svc:8002
    depends_on:
      - recommender-svc

  recommender-svc:
    build: ./recommender-svc
    container_name: recommender-svc
    ports:
      - "8002:8002"